In [1]:
import pandas as pd
import numpy as np

books = pd.read_csv("books_with_categories.csv")

In [2]:
    books

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count,title_and_subtitle,tagged_description,simple_categories
0,9780002005883,0002005883,Gilead,Marilynne Robinson,Fiction,http://books.google.com/books/content?id=KQZCP...,A NOVEL THAT READERS and critics have been eag...,2004.0,3.85,247.0,361.0,Gilead,9780002005883 A NOVEL THAT READERS and critics...,Fiction
1,9780002261982,0002261987,Spider's Web,Charles Osborne;Agatha Christie,Detective and mystery stories,http://books.google.com/books/content?id=gA5GP...,A new 'Christie for Christmas' -- a full-lengt...,2000.0,3.83,241.0,5164.0,Spider's Web: A Novel,9780002261982 A new 'Christie for Christmas' -...,Fiction
2,9780006178736,0006178731,Rage of angels,Sidney Sheldon,Fiction,http://books.google.com/books/content?id=FKo2T...,"A memorable, mesmerizing heroine Jennifer -- b...",1993.0,3.93,512.0,29532.0,Rage of angels,"9780006178736 A memorable, mesmerizing heroine...",Fiction
3,9780006280897,0006280897,The Four Loves,Clive Staples Lewis,Christian life,http://books.google.com/books/content?id=XhQ5X...,Lewis' work on the nature of love divides love...,2002.0,4.15,170.0,33684.0,The Four Loves,9780006280897 Lewis' work on the nature of lov...,Nonfiction
4,9780006280934,0006280935,The Problem of Pain,Clive Staples Lewis,Christian life,http://books.google.com/books/content?id=Kk-uV...,"""In The Problem of Pain, C.S. Lewis, one of th...",2002.0,4.09,176.0,37569.0,The Problem of Pain,"9780006280934 ""In The Problem of Pain, C.S. Le...",Nonfiction
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5192,9788172235222,8172235224,Mistaken Identity,Nayantara Sahgal,Indic fiction (English),http://books.google.com/books/content?id=q-tKP...,On A Train Journey Home To North India After L...,2003.0,2.93,324.0,0.0,Mistaken Identity,9788172235222 On A Train Journey Home To North...,Fiction
5193,9788173031014,8173031010,Journey to the East,Hermann Hesse,Adventure stories,http://books.google.com/books/content?id=rq6JP...,This book tells the tale of a man who goes on ...,2002.0,3.70,175.0,24.0,Journey to the East,9788173031014 This book tells the tale of a ma...,Nonfiction
5194,9788179921623,817992162X,The Monk Who Sold His Ferrari: A Fable About F...,Robin Sharma,Health & Fitness,http://books.google.com/books/content?id=c_7mf...,"Wisdom to Create a Life of Passion, Purpose, a...",2003.0,3.82,198.0,1568.0,The Monk Who Sold His Ferrari: A Fable About F...,9788179921623 Wisdom to Create a Life of Passi...,Fiction
5195,9788185300535,8185300534,I Am that,Sri Nisargadatta Maharaj;Sudhakar S. Dikshit,Philosophy,http://books.google.com/books/content?id=Fv_JP...,This collection of the timeless teachings of o...,1999.0,4.51,531.0,104.0,I Am that: Talks with Sri Nisargadatta Maharaj,9788185300535 This collection of the timeless ...,Nonfiction
5196,9789027712059,9027712050,The Berlin Phenomenology,Georg Wilhelm Friedrich Hegel,History,http://books.google.com/books/content?id=Vy7Sk...,Since the three volume edition ofHegel's Philo...,1981.0,0.00,210.0,0.0,The Berlin Phenomenology,9789027712059 Since the three volume edition o...,Nonfiction

In [3]:
from transformers import pipeline
classifier = pipeline("text-classification", model="j-hartmann/emotion-english-distilroberta-base", top_k= None)
classifier("I love this!")

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Loading weights:   0%|          | 0/105 [00:00<?, ?it/s]

RobertaForSequenceClassification LOAD REPORT from: j-hartmann/emotion-english-distilroberta-base
Key                             | Status     |  |
--------------------------------+------------+--+-
roberta.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

[[{'label': 'joy', 'score': 0.9771687984466553},
  {'label': 'surprise', 'score': 0.008528688922524452},
  {'label': 'neutral', 'score': 0.005764589179307222},
  {'label': 'anger', 'score': 0.004419790115207434},
  {'label': 'sadness', 'score': 0.002092392183840275},
  {'label': 'disgust', 'score': 0.001611991785466671},
  {'label': 'fear', 'score': 0.0004138524236623198}]]

In [4]:
books["description"][0]

'A NOVEL THAT READERS and critics have been eagerly anticipating for over a decade, Gilead is an astonishingly imagined story of remarkable lives. John Ames is a preacher, the son of a preacher and the grandson (both maternal and paternal) of preachers. It’s 1956 in Gilead, Iowa, towards the end of the Reverend Ames’s life, and he is absorbed in recording his family’s story, a legacy for the young son he will never see grow up. Haunted by his grandfather’s presence, John tells of the rift between his grandfather and his father: the elder, an angry visionary who fought for the abolitionist cause, and his son, an ardent pacifist. He is troubled, too, by his prodigal namesake, Jack (John Ames) Boughton, his best friend’s lost son who returns to Gilead searching for forgiveness and redemption. Told in John Ames’s joyous, rambling voice that finds beauty, humour and truth in the smallest of life’s details, Gilead is a song of celebration and acceptance of the best and the worst the world has to offer. At its heart is a tale of the sacred bonds between fathers and sons, pitch-perfect in style and story, set to dazzle critics and readers alike.'

In [5]:
classifier(books["description"][0])

[[{'label': 'fear', 'score': 0.6548401713371277},
  {'label': 'neutral', 'score': 0.16985252499580383},
  {'label': 'sadness', 'score': 0.11640933156013489},
  {'label': 'surprise', 'score': 0.020700689405202866},
  {'label': 'disgust', 'score': 0.01910070702433586},
  {'label': 'joy', 'score': 0.015161466784775257},
  {'label': 'anger', 'score': 0.0039351508021354675}]]

In [6]:
classifier(books["description"][0].split("."))

[[{'label': 'surprise', 'score': 0.7296023368835449},
  {'label': 'neutral', 'score': 0.14038589596748352},
  {'label': 'fear', 'score': 0.06816226243972778},
  {'label': 'joy', 'score': 0.047942522913217545},
  {'label': 'anger', 'score': 0.00915636494755745},
  {'label': 'disgust', 'score': 0.002628474961966276},
  {'label': 'sadness', 'score': 0.0021221614442765713}],
 [{'label': 'neutral', 'score': 0.4493703842163086},
  {'label': 'disgust', 'score': 0.2735915184020996},
  {'label': 'joy', 'score': 0.10908320546150208},
  {'label': 'sadness', 'score': 0.09362740069627762},
  {'label': 'anger', 'score': 0.04047832638025284},
  {'label': 'surprise', 'score': 0.02697017230093479},
  {'label': 'fear', 'score': 0.006879048887640238}],
 [{'label': 'neutral', 'score': 0.6462150812149048},
  {'label': 'sadness', 'score': 0.24273402988910675},
  {'label': 'disgust', 'score': 0.04342275485396385},
  {'label': 'surprise', 'score': 0.028300579637289047},
  {'label': 'joy', 'score': 0.014211492612957954},
  {'label': 'fear', 'score': 0.014084121212363243},
  {'label': 'anger', 'score': 0.011031919158995152}],
 [{'label': 'fear', 'score': 0.9281681180000305},
  {'label': 'anger', 'score': 0.03219105303287506},
  {'label': 'neutral', 'score': 0.012808670289814472},
  {'label': 'sadness', 'score': 0.008756876923143864},
  {'label': 'surprise', 'score': 0.00859791599214077},
  {'label': 'disgust', 'score': 0.008431825786828995},
  {'label': 'joy', 'score': 0.001045584212988615}],
 [{'label': 'sadness', 'score': 0.9671575427055359},
  {'label': 'neutral', 'score': 0.015104157850146294},
  {'label': 'disgust', 'score': 0.00648059556260705},
  {'label': 'fear', 'score': 0.005393987521529198},
  {'label': 'surprise', 'score': 0.0022869398817420006},
  {'label': 'anger', 'score': 0.001842890284024179},
  {'label': 'joy', 'score': 0.0017338789766654372}],
 [{'label': 'joy', 'score': 0.9327982664108276},
  {'label': 'disgust', 'score': 0.03771696984767914},
  {'label': 'neutral', 'score': 0.015891820192337036},
  {'label': 'sadness', 'score': 0.006444491911679506},
  {'label': 'anger', 'score': 0.005024959798902273},
  {'label': 'surprise', 'score': 0.0015812052879482508},
  {'label': 'fear', 'score': 0.0005423057591542602}],
 [{'label': 'joy', 'score': 0.6528707146644592},
  {'label': 'neutral', 'score': 0.25427478551864624},
  {'label': 'surprise', 'score': 0.06808292120695114},
  {'label': 'sadness', 'score': 0.00990898534655571},
  {'label': 'disgust', 'score': 0.006512219086289406},
  {'label': 'anger', 'score': 0.004821308422833681},
  {'label': 'fear', 'score': 0.0035290136002004147}],
 [{'label': 'neutral', 'score': 0.549476683139801},
  {'label': 'sadness', 'score': 0.1116902306675911},
  {'label': 'disgust', 'score': 0.10400674492120743},
  {'label': 'surprise', 'score': 0.07876548171043396},
  {'label': 'anger', 'score': 0.0641336664557457},
  {'label': 'fear', 'score': 0.051362838596105576},
  {'label': 'joy', 'score': 0.04056441783905029}]]

In [7]:
sentences = books["description"][0].split(".")
predictions = classifier(sentences)

In [8]:
sentences[3]

' Haunted by his grandfather’s presence, John tells of the rift between his grandfather and his father: the elder, an angry visionary who fought for the abolitionist cause, and his son, an ardent pacifist'

In [9]:
predictions[3]

[{'label': 'fear', 'score': 0.9281681180000305},
 {'label': 'anger', 'score': 0.03219105303287506},
 {'label': 'neutral', 'score': 0.012808670289814472},
 {'label': 'sadness', 'score': 0.008756876923143864},
 {'label': 'surprise', 'score': 0.00859791599214077},
 {'label': 'disgust', 'score': 0.008431825786828995},
 {'label': 'joy', 'score': 0.001045584212988615}]

In [10]:
predictions

[[{'label': 'surprise', 'score': 0.7296023368835449},
  {'label': 'neutral', 'score': 0.14038589596748352},
  {'label': 'fear', 'score': 0.06816226243972778},
  {'label': 'joy', 'score': 0.047942522913217545},
  {'label': 'anger', 'score': 0.00915636494755745},
  {'label': 'disgust', 'score': 0.002628474961966276},
  {'label': 'sadness', 'score': 0.0021221614442765713}],
 [{'label': 'neutral', 'score': 0.4493703842163086},
  {'label': 'disgust', 'score': 0.2735915184020996},
  {'label': 'joy', 'score': 0.10908320546150208},
  {'label': 'sadness', 'score': 0.09362740069627762},
  {'label': 'anger', 'score': 0.04047832638025284},
  {'label': 'surprise', 'score': 0.02697017230093479},
  {'label': 'fear', 'score': 0.006879048887640238}],
 [{'label': 'neutral', 'score': 0.6462150812149048},
  {'label': 'sadness', 'score': 0.24273402988910675},
  {'label': 'disgust', 'score': 0.04342275485396385},
  {'label': 'surprise', 'score': 0.028300579637289047},
  {'label': 'joy', 'score': 0.014211492612957954},
  {'label': 'fear', 'score': 0.014084121212363243},
  {'label': 'anger', 'score': 0.011031919158995152}],
 [{'label': 'fear', 'score': 0.9281681180000305},
  {'label': 'anger', 'score': 0.03219105303287506},
  {'label': 'neutral', 'score': 0.012808670289814472},
  {'label': 'sadness', 'score': 0.008756876923143864},
  {'label': 'surprise', 'score': 0.00859791599214077},
  {'label': 'disgust', 'score': 0.008431825786828995},
  {'label': 'joy', 'score': 0.001045584212988615}],
 [{'label': 'sadness', 'score': 0.9671575427055359},
  {'label': 'neutral', 'score': 0.015104157850146294},
  {'label': 'disgust', 'score': 0.00648059556260705},
  {'label': 'fear', 'score': 0.005393987521529198},
  {'label': 'surprise', 'score': 0.0022869398817420006},
  {'label': 'anger', 'score': 0.001842890284024179},
  {'label': 'joy', 'score': 0.0017338789766654372}],
 [{'label': 'joy', 'score': 0.9327982664108276},
  {'label': 'disgust', 'score': 0.03771696984767914},
  {'label': 'neutral', 'score': 0.015891820192337036},
  {'label': 'sadness', 'score': 0.006444491911679506},
  {'label': 'anger', 'score': 0.005024959798902273},
  {'label': 'surprise', 'score': 0.0015812052879482508},
  {'label': 'fear', 'score': 0.0005423057591542602}],
 [{'label': 'joy', 'score': 0.6528707146644592},
  {'label': 'neutral', 'score': 0.25427478551864624},
  {'label': 'surprise', 'score': 0.06808292120695114},
  {'label': 'sadness', 'score': 0.00990898534655571},
  {'label': 'disgust', 'score': 0.006512219086289406},
  {'label': 'anger', 'score': 0.004821308422833681},
  {'label': 'fear', 'score': 0.0035290136002004147}],
 [{'label': 'neutral', 'score': 0.549476683139801},
  {'label': 'sadness', 'score': 0.1116902306675911},
  {'label': 'disgust', 'score': 0.10400674492120743},
  {'label': 'surprise', 'score': 0.07876548171043396},
  {'label': 'anger', 'score': 0.0641336664557457},
  {'label': 'fear', 'score': 0.051362838596105576},
  {'label': 'joy', 'score': 0.04056441783905029}]]

In [11]:
sorted(predictions[0], key=lambda x: x["label"])

[{'label': 'anger', 'score': 0.00915636494755745},
 {'label': 'disgust', 'score': 0.002628474961966276},
 {'label': 'fear', 'score': 0.06816226243972778},
 {'label': 'joy', 'score': 0.047942522913217545},
 {'label': 'neutral', 'score': 0.14038589596748352},
 {'label': 'sadness', 'score': 0.0021221614442765713},
 {'label': 'surprise', 'score': 0.7296023368835449}]

In [28]:
emotion_labels = ["anger","disgust","fear","joy","sadness","surpise","neutral"]
isbn = []

emotion_scores = {label: [] for label in emotion_labels}

In [13]:
def calculate_max_emotion_score(predictions):
    per_emotion_scores = {label: [] for label in emotion_labels}
    for prediction in predictions:
        sorted_prediction = sorted(prediction, key=lambda x: x["label"])
        for index, label in enumerate(emotion_labels):
            per_emotion_scores[label].append(sorted_prediction[index]["score"])
    return {label: np.max(scores) for label, scores in per_emotion_scores.items()}

In [14]:
for i in range(10):
    isbn.append(books["isbn13"][i])
    sentences = books["description"][i].split(".")
    predictions = classifier(sentences)
    max_scores = calculate_max_emotion_score(predictions)
    for label in emotion_labels:
        emotion_scores[label].append(max_scores[label])

In [15]:
emotion_scores

{'anger': [np.float64(0.0641336664557457),
  np.float64(0.6126194596290588),
  np.float64(0.0641336664557457),
  np.float64(0.351485013961792),
  np.float64(0.08141247928142548),
  np.float64(0.23222415149211884),
  np.float64(0.5381836295127869),
  np.float64(0.0641336664557457),
  np.float64(0.3006701171398163),
  np.float64(0.0641336664557457)],
 'disgust': [np.float64(0.2735915184020996),
  np.float64(0.3482842445373535),
  np.float64(0.10400674492120743),
  np.float64(0.15072223544120789),
  np.float64(0.18449555337429047),
  np.float64(0.7271754741668701),
  np.float64(0.1558547466993332),
  np.float64(0.10400674492120743),
  np.float64(0.2794811725616455),
  np.float64(0.1779259592294693)],
 'fear': [np.float64(0.9281681180000305),
  np.float64(0.9425276517868042),
  np.float64(0.9723207950592041),
  np.float64(0.3607054352760315),
  np.float64(0.09504346549510956),
  np.float64(0.051362838596105576),
  np.float64(0.7474274635314941),
  np.float64(0.40449732542037964),
  np.float64(0.9155241250991821),
  np.float64(0.051362838596105576)],
 'joy': [np.float64(0.9327982664108276),
  np.float64(0.704422116279602),
  np.float64(0.7672379016876221),
  np.float64(0.25188130140304565),
  np.float64(0.04056441783905029),
  np.float64(0.04337579756975174),
  np.float64(0.872565746307373),
  np.float64(0.04056441783905029),
  np.float64(0.04056441783905029),
  np.float64(0.04056441783905029)],
 'sadness': [np.float64(0.6462150812149048),
  np.float64(0.8879393339157104),
  np.float64(0.549476683139801),
  np.float64(0.732684850692749),
  np.float64(0.8843896985054016),
  np.float64(0.6213915348052979),
  np.float64(0.7121940851211548),
  np.float64(0.549476683139801),
  np.float64(0.8402894735336304),
  np.float64(0.8603723645210266)],
 'surpise': [np.float64(0.9671575427055359),
  np.float64(0.1116902306675911),
  np.float64(0.1116902306675911),
  np.float64(0.1116902306675911),
  np.float64(0.47588032484054565),
  np.float64(0.1116902306675911),
  np.float64(0.40800049901008606),
  np.float64(0.8202820420265198),
  np.float64(0.3544616997241974),
  np.float64(0.1116902306675911)],
 'neutral': [np.float64(0.7296023368835449),
  np.float64(0.252546101808548),
  np.float64(0.07876548171043396),
  np.float64(0.07876548171043396),
  np.float64(0.07876548171043396),
  np.float64(0.2719038724899292),
  np.float64(0.07876548171043396),
  np.float64(0.23448680341243744),
  np.float64(0.13561373949050903),
  np.float64(0.07876548171043396)]}

In [36]:
from tqdm import tqdm

emotion_labels = ["anger","disgust","fear","joy","sadness","surpise","neutral"]
isbn = []

for i in tqdm(range(len(books))):
    isbn.append(books["isbn13"][i])
    sentences = books["description"][i].split(".")
    predictions = classifier(sentences)
    max_scores = calculate_max_emotion_score(predictions)
    for label in emotion_labels:
        emotion_scores[label].append(max_scores[label])

100%|██████████| 5197/5197 [27:26<00:00,  3.16it/s]

In [37]:
emotions_df = pd.DataFrame(emotion_scores)
emotions_df["isbn13"] = isbn

In [40]:
emotions_df.head(20)

,anger,disgust,fear,joy,sadness,surpise,neutral,isbn13
0,0.064134,0.273592,0.928168,0.932798,0.646215,0.967158,0.729602,9780002005883
1,0.612619,0.348284,0.942528,0.704422,0.887939,0.111690,0.252546,9780002261982
2,0.064134,0.104007,0.972321,0.767238,0.549477,0.111690,0.078765,9780006178736
3,0.351485,0.150722,0.360705,0.251881,0.732685,0.111690,0.078765,9780006280897
4,0.081412,0.184496,0.095043,0.040564,0.884390,0.475880,0.078765,9780006280934
5,0.232224,0.727175,0.051363,0.043376,0.621392,0.111690,0.271904,9780006380832
6,0.538184,0.155855,0.747427,0.872566,0.712194,0.408000,0.078765,9780006470229
7,0.064134,0.104007,0.404497,0.040564,0.549477,0.820282,0.234487,9780006472612
8,0.300670,0.279481,0.915524,0.040564,0.840289,0.354462,0.135614,9780006482079
9,0.064134,0.177926,0.051363,0.040564,0.860372,0.111690,0.078765,9780006483014
10,0.064134,0.104007,0.051363,0.368068,0.909297,0.160302,0.164458,9780006483892
11,0.611575,0.280444,0.929688,0.040564,0.549477,0.392193,0.078765,9780006483908
12,0.106216,0.129205,0.981006,0.504204,0.714712,0.122541,0.078765,9780006486145
13,0.064134,0.104007,0.948645,0.905534,0.568445,0.856202,0.245933,9780006490456
14,0.072393,0.116416,0.953626,0.509408,0.549477,0.841214,0.803091,9780006496434
15,0.095864,0.025358,0.812283,0.003585,0.051311,0.802916,0.006833,9780006496878
16,0.162159,0.479785,0.051363,0.040564,0.549477,0.175309,0.078765,9780006496892
17,0.064134,0.104007,0.051363,0.720229,0.549477,0.111690,0.078765,9780006496922
18,0.081938,0.157167,0.976755,0.550421,0.568199,0.111690,0.078765,9780006498865
19,0.223461,0.162839,0.817495,0.929979,0.636295,0.429466,0.078765,9780006499169

In [41]:
books = pd.merge(books, emotions_df, on="isbn13")

In [42]:
books.head(5)

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,...,title_and_subtitle,tagged_description,simple_categories,anger,disgust,fear,joy,sadness,surpise,neutral
0,9780002005883,0002005883,Gilead,Marilynne Robinson,Fiction,http://books.google.com/books/content?id=KQZCP...,A NOVEL THAT READERS and critics have been eag...,2004.0,3.85,247.0,...,Gilead,9780002005883 A NOVEL THAT READERS and critics...,Fiction,0.064134,0.273592,0.928168,0.932798,0.646215,0.967158,0.729602
1,9780002261982,0002261987,Spider's Web,Charles Osborne;Agatha Christie,Detective and mystery stories,http://books.google.com/books/content?id=gA5GP...,A new 'Christie for Christmas' -- a full-lengt...,2000.0,3.83,241.0,...,Spider's Web: A Novel,9780002261982 A new 'Christie for Christmas' -...,Fiction,0.612619,0.348284,0.942528,0.704422,0.887939,0.111690,0.252546
2,9780006178736,0006178731,Rage of angels,Sidney Sheldon,Fiction,http://books.google.com/books/content?id=FKo2T...,"A memorable, mesmerizing heroine Jennifer -- b...",1993.0,3.93,512.0,...,Rage of angels,"9780006178736 A memorable, mesmerizing heroine...",Fiction,0.064134,0.104007,0.972321,0.767238,0.549477,0.111690,0.078765
3,9780006280897,0006280897,The Four Loves,Clive Staples Lewis,Christian life,http://books.google.com/books/content?id=XhQ5X...,Lewis' work on the nature of love divides love...,2002.0,4.15,170.0,...,The Four Loves,9780006280897 Lewis' work on the nature of lov...,Nonfiction,0.351485,0.150722,0.360705,0.251881,0.732685,0.111690,0.078765
4,9780006280934,0006280935,The Problem of Pain,Clive Staples Lewis,Christian life,http://books.google.com/books/content?id=Kk-uV...,"""In The Problem of Pain, C.S. Lewis, one of th...",2002.0,4.09,176.0,...,The Problem of Pain,"9780006280934 ""In The Problem of Pain, C.S. Le...",Nonfiction,0.081412,0.184496,0.095043,0.040564,0.884390,0.475880,0.078765

In [43]:
books.to_csv("books_with_emotion.csv", index = False)